name: Deploy Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18' }
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build React app
        run: cd frontend && npm run build
      - name: Copy to docs
        run: |
          rm -rf docs/*
          cp -r frontend/build/* docs/
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/*
          git commit -m "Deploy React app to docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}