name: Deploy Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to docs
        run: |
          mkdir -p docs
          cp *.html docs/ 2>/dev/null || true
          echo "Deployed $(date)" > docs/README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git diff --staged --quiet || git commit -m "Deploy to GitHub Pages"
          git push